### ISSUE TITLE
undefined method `name=' for #<Matrix

### ISSUE THREAD

**Issue by g3d** [gbiczo/oxcelix#6] opened 2015-03-25 14:33 UTC
```ruby
::Oxcelix::Workbook.new('import.xlsx')
NoMethodError: undefined method `name=' for #<Matrix:0x0000014bea92b8>
from /Users/g3d/.rvm/gems/ruby-2.1.1@isis/gems/oxcelix-0.4.0/lib/oxcelix/workbook.rb:277:in `block in matrixto'
```

**Comment by gbiczo** [comment] 2015-03-25 22:43
Hello there,
Would need some more info to be able to check the issue, such as:
have you tried with any other excel file?
how is the structure of the 'import.xlsx' file?
ever tried to open a file with similar structure (like: same tab names w different data and so on)?
Thank you!

**Comment by gbiczo** [comment] 2015-06-16 19:44
Cannot reproduce, no answers received, closing.

**Closed by gbiczo** 2015-06-16 19:44 UTC
